// Get all users
GET https://gaming-token-production.up.railway.app/api/v1/user

###
GET https://gaming-token-production.up.railway.app/api/v1/user/2

###
// Register
POST https://gaming-token-production.up.railway.app/api/v1/user/register
Content-Type: application/json

{
    "userName": "wer", 
    "password": "1234"
}

###
// Login
POST https://gaming-token-production.up.railway.app/api/v1/user/login
Content-Type: application/json

{
    "userName": "waq",
    "password": "12345678"
}

###
// Logout
GET https://gaming-token-production.up.railway.app/api/v1/user/logout

###
// Check if user is logged in
GET https://gaming-token-production.up.railway.app/api/v1/user/check-session

###
// Request an airdrop
POST https://gaming-token-production.up.railway.app/api/v1/user/airdrop
Content-Type: application/json

###
// Transfer tokens
POST https://gaming-token-production.up.railway.app/api/v1/user/transfer
Content-Type: application/json

{
    "to": "65d2e95223c29596a324a832",
    "amount": 4.25
}

### 
// View balance by user id
GET https://gaming-token-production.up.railway.app/api/v1/user/65d6950a04ddc6c2b1d76c9f/balance



###
// View user's transactions
GET https://gaming-token-production.up.railway.app/api/v1/user/transactions/65d6950a04ddc6c2b1d76c9f


###
// Get user by session id
GET https://gaming-token-production.up.railway.app/api/v1/user/getUser







